apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus.vibecheck.svc.cluster.local:9090
    isDefault: true
    editable: false
